echo off
echo Ý
echo ÝThank you for your purchase of Moraff's World. This is a large game, designed
echo Ýfor fast computers, hard drives and high-res monitors. However, we have made
echo Ýsome effort to support older equipment, and World's requirements follow:
echo Ý
echo ÝOne 360K drive, Herc, CGA, EGA, VGA or better, full 640K RAM.
echo ÝWe recommend, however, a hard drive, VGA and a fast 286.
echo Ý
echo ÝDirections:   First make a backup copy of the disk or diskettes.
echo ÝTo use World on a hard drive, simply copy the entire game into a directory.
echo Ý  Example:  [C:\]md mw,   [C:\]cd mw,  [C:\MW]copy a:*.*,  [C:\MW]mw
echo ÝIf this program is on 360K diskettes, you will have to use the copy command
echo Ý  on both disks.
echo ÝTo use world on a 720, 1.2 or 1.44 floppy drive, simply insert the disk and
echo Ý  type `mw'.
echo ÝTo use World on a 360K drive, insert the GAME disk and type `mw'. Note that
echo Ý  you are limited to one character per game disk.
echo Ý
echo ÝIf you are running any memory resident programs, you may have to remove them
echo Ý  to run Moraff's World. World requires a full 640k and only runs in base RAM.
echo Ý
echo ÝPlease do not use your master disks as play disks. Use copies of the masters.
echo Ý
